"""Generate reports/eda_report.md — the evidence base for the writeup (D).

Focuses on the five assumption-violations that define the challenge, with
hard numbers we can cite in Deliverable D:
  1. selective labels (outcomes only for prior-approved)
  2. censoring (matured vs open)
  3. MNAR missingness (bank feed)
  4. optimistic self-report bias (stated vs observed revenue)
  5. default timing distribution (why B / NPV need time, not a yes/no)
"""
from __future__ import annotations

import io

import numpy as np
import pandas as pd

from . import data, paths


def _fmt_pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def build_report() -> str:
    tr = data.load_train()
    va = data.load_validation()
    te = data.load_test()
    buf = io.StringIO()
    P = lambda *a: print(*a, file=buf)

    P("# EDA Report — SMB Underwriting Challenge\n")
    P("_Auto-generated by `src/eda.py`. Numbers here back Deliverable D._\n")

    # ---- shapes ----
    P("## 0. Shapes\n")
    P("| frame | rows | cols |")
    P("|---|---|---|")
    for name, df in (("train", tr), ("validation", va), ("test", te)):
        P(f"| {name} | {len(df):,} | {df.shape[1]} |")
    P(f"\nValidation + test = **{len(va) + len(te):,}** applicants (Deliverable A universe).\n")

    # ---- 1. selective labels ----
    P("## 1. Selective labels / sample-selection bias\n")
    approved = data.approval_indicator(tr)
    n_app = int((approved == 1).sum())
    n_dec = int((approved == 0).sum())
    P(f"- Prior-**approved** (outcomes observed): **{n_app:,}** ({_fmt_pct(n_app/len(tr))})")
    P(f"- Prior-**declined** (outcomes blank, UNLABELED): **{n_dec:,}** ({_fmt_pct(n_dec/len(tr))})")
    lab = data.build_survival_label(tr)
    n_lab = int(lab["has_label"].sum())
    n_evt = int(lab.loc[lab.has_label, "event"].sum())
    P(f"- Usable survival labels: **{n_lab:,}**, of which defaults: **{n_evt:,}** "
      f"(**{_fmt_pct(n_evt/max(n_lab,1))}** default rate among approved).")
    P("\n> Naive training learns P(default | approved), not P(default | applied). "
      "`prior_decision` / `prior_underwriter_score` are the selection mechanism; "
      "we correct via propensity-of-approval IPW (see methodology).\n")

    # feature drift approved vs declined (a few key cols)
    P("**Feature drift, approved vs declined (mean):**\n")
    P("| feature | approved | declined |")
    P("|---|---|---|")
    for c in ["prior_underwriter_score", "aggregate_credit_utilization",
              "requested_amount", "recent_inquiries_count_6mo"]:
        if c in tr.columns:
            ma = tr.loc[approved == 1, c].astype(float).mean()
            md = tr.loc[approved == 0, c].astype(float).mean()
            P(f"| {c} | {ma:,.3f} | {md:,.3f} |")
    P("")

    # ---- 2. censoring ----
    P("## 2. Censoring\n")
    if "observation_status" in tr.columns:
        vc = tr["observation_status"].value_counts(dropna=False)
        for k, v in vc.items():
            P(f"- observation_status = {k!r}: {v:,}")
    if "repayment_status" in tr.columns:
        P("")
        vc = tr["repayment_status"].value_counts(dropna=False)
        for k, v in vc.items():
            P(f"- repayment_status = {k!r}: {v:,}")
    P("\n> Paid-in-full loans are censored at repayment (never defaulted); immature/"
      "declined loans carry no event and are excluded from the survival fit.\n")

    # ---- 3. MNAR missingness ----
    P("## 3. MNAR missingness\n")
    if "has_linked_bank_feed" in tr.columns:
        feed = tr["has_linked_bank_feed"].astype(float).mean()
        P(f"- `has_linked_bank_feed` true rate: **{_fmt_pct(feed)}** "
          f"→ ~{_fmt_pct(1-feed)} of bank-feed columns structurally null.\n")
    P("**Null rate by feature (train, >0 only):**\n")
    P("| feature | null rate |")
    P("|---|---|")
    nulls = tr[data.feature_columns()].isna().mean().sort_values(ascending=False)
    for c, r in nulls[nulls > 0].items():
        P(f"| {c} | {_fmt_pct(r)} |")
    P("\n> Missingness is informative (MNAR): we add explicit `*_is_missing` flags "
      "rather than imputing it away. Candidate flag columns:\n")
    P("`" + ", ".join(data.nullable_feature_columns()) + "`\n")

    # ---- 4. self-report bias ----
    P("## 4. Optimistic self-report bias\n")
    if {"stated_annual_revenue", "observed_monthly_revenue_avg_3mo"} <= set(tr.columns):
        sub = tr.loc[tr["has_linked_bank_feed"] == True].copy()  # noqa: E712
        stated_monthly = sub["stated_annual_revenue"].astype(float) / 12.0
        observed = sub["observed_monthly_revenue_avg_3mo"].astype(float)
        ratio = (stated_monthly / observed).replace([np.inf, -np.inf], np.nan).dropna()
        P(f"- Among feed-linked rows, stated monthly revenue / observed monthly "
          f"revenue — median **{ratio.median():.2f}**, mean **{ratio.mean():.2f}** "
          f"(>1 ⇒ applicants over-state).\n")

    # ---- 5. timing ----
    P("## 5. Default timing (why B / NPV need time)\n")
    dtd = tr["days_to_default"].dropna().astype(float)
    P(f"- `days_to_default`: n={len(dtd):,}, min={dtd.min():.0f}, "
      f"median={dtd.median():.0f}, mean={dtd.mean():.1f}, max={dtd.max():.0f}")
    qs = dtd.quantile([0.1, 0.25, 0.5, 0.75, 0.9])
    P("- deciles/quartiles: " + ", ".join(f"p{int(q*100)}={v:.0f}" for q, v in qs.items()))
    early = float((dtd <= 7).mean())
    P(f"- **{_fmt_pct(early)}** of defaults occur in the first 7 days (catastrophic "
      "for NPV); a day-55 default is near break-even. A yes/no classifier cannot "
      "tell these apart — hence the shared survival model.\n")

    return buf.getvalue()


def write_report(path=None) -> str:
    path = path or (paths.REPORTS_DIR / "eda_report.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    text = build_report()
    path.write_text(text, encoding="utf-8")
    print(f"EDA report written to {path}")
    return text


if __name__ == "__main__":
    write_report()
