"""Phase 5 — rigorous optimization to maximize P&L (+ calibration + trajectory).

Pipeline (every choice measured on OUT-OF-FOLD data, GroupKFold by business_id):
  1. Richer credit-risk features.
  2. OOF base learners (lgbm / xgb / hgb / logistic), then a STACKED meta-learner.
  3. Recovery model (per-loan recovery fraction) -> sharper E[NPV].
  4. Calibrate on OOF (20x more data than val) + tune the approval threshold on OOF P&L.
  5. Refit on all labeled, score test, regenerate A & B. (C regenerated by phase3.)

Run:  python run.py phase5
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.metrics import brier_score_loss, roc_auc_score

from . import (calibrate, cohorts, cv, data, evaluate, features, models, npv,
               paths, submission, survival, validate)

N_WEEKS = cohorts.N_WEEKS
BASES = ["lgbm", "xgb", "hgb", "logistic"]
Z = 1.645


def _pnl_for(pd_oof, y, wk, R, day_per_week, recrate, labeled):
    """Calibrate OOF PD, tune threshold on OOF realized P&L, return summary."""
    cal = calibrate.fit_pd_calibrator(pd_oof, y, "platt")
    cpd = cal.predict(pd_oof)
    enpv = cv.enpv_from_pd(cpd, wk, R, day_per_week, recrate)
    tb = evaluate.tune_buffer(labeled, enpv)
    return {"auc": roc_auc_score(y, pd_oof), "brier": brier_score_loss(y, np.clip(cpd, 1e-6, 1 - 1e-6)),
            "pnl": tb["pnl_at_tau"], "tau": tb["tau"], "approve": tb["approve_rate"]}


def run() -> bool:
    print("=" * 74, "\nPHASE 5 — rigorous optimization (CV stack + recovery + OOF calibration)\n" + "=" * 74)
    tr, va, te = data.load_train(), data.load_validation(), data.load_test()
    labeled = tr[data.build_survival_label(tr)["has_label"].to_numpy()].copy()
    X, fs = features.build_features(labeled)
    y = labeled["default_flag"].astype(int).to_numpy()
    groups = labeled["business_id"].to_numpy()
    R = labeled["requested_amount"].to_numpy(float)
    print(f"labeled={len(labeled):,} | features={X.shape[1]} | businesses={len(np.unique(groups)):,}")

    # ---- 1-2. OOF base learners + stack ----
    print("\n[OOF base learners — GroupKFold(business_id), k=5]")
    base_oof = {}
    for b in BASES:
        oof, _ = cv.oof_predict(b, X, y, groups, fs.columns, k=5)
        base_oof[b] = oof
        print(f"   {b:9s} OOF AUC={roc_auc_score(y, oof):.4f}  Brier={brier_score_loss(y, oof):.4f}")
    stack_oof, meta = cv.stack_oof(base_oof, y)
    print(f"   {'STACK':9s} OOF AUC={roc_auc_score(y, stack_oof):.4f}  Brier={brier_score_loss(y, stack_oof):.4f}")

    # ---- 3. recovery + timing (for E[NPV]) ----
    recmodel = cv.fit_recovery(labeled, fs)
    tm, classes, day_per_week = cv.week_probs_global(labeled, fs)
    wk_lab = cv.expand_week_probs(tm, classes, X)
    recrate_lab = cv.recovery_rate(recmodel, X)
    rec_flat = survival.recovery_rate_from(tr)
    print(f"\nrecovery model: mean pred={recrate_lab.mean():.3f} (flat was {rec_flat:.3f})")

    # ---- 4. honest OOF P&L: single logistic vs stack; flat vs modelled recovery ----
    print("\n[OOF realized P&L (honest, threshold tuned on OOF)]")
    res = {}
    res["logistic"] = _pnl_for(base_oof["logistic"], y, wk_lab, R, day_per_week, recrate_lab, labeled)
    res["stack"] = _pnl_for(stack_oof, y, wk_lab, R, day_per_week, recrate_lab, labeled)
    res["stack(flatRec)"] = _pnl_for(stack_oof, y, wk_lab, R, day_per_week, rec_flat, labeled)
    for nm, r in res.items():
        print(f"   {nm:15s} AUC={r['auc']:.4f} Brier={r['brier']:.4f} "
              f"tau=${r['tau']:,.0f} approve={r['approve']:.3f} OOF_P&L=${r['pnl']:,.0f}")
    winner = "stack" if res["stack"]["pnl"] >= res["logistic"]["pnl"] else "logistic"
    print(f"   >>> PD source = {winner}  (OOF P&L ${res[winner]['pnl']:,.0f})")

    # ---- 5. final model on ALL labeled ----
    final_base = {b: models.make_backbone(b, fs.columns, seed=0).fit(X, y) for b in BASES}
    cal = calibrate.fit_pd_calibrator(stack_oof if winner == "stack" else base_oof["logistic"], y, "platt")
    tau = res[winner]["tau"]
    kA = calibrate.tune_pd_interval(cal.predict(stack_oof if winner == "stack" else base_oof["logistic"]), y)
    print(f"\nfinal: PD={winner} | calibrator=platt | tau=${tau:,.0f} | A-interval k={kA['k']:.2f} floor={kA['floor']} "
          f"| OOF A-cov={kA['coverage']:.2f}")

    # ---- score pool ----
    pool = pd.concat([va, te], ignore_index=True)
    Xp, _ = features.build_features(pool, fs)
    base_p = {b: models.proba(final_base[b], Xp) for b in BASES}
    stack_p = cv.apply_stack(meta, base_p)
    raw_p = stack_p if winner == "stack" else base_p["logistic"]
    cpd = cal.predict(raw_p)
    wk_cond = cv.expand_week_probs(tm, classes, Xp)
    rec_p = cv.recovery_rate(recmodel, Xp)
    enpv = cv.enpv_from_pd(cpd, wk_cond, pool["requested_amount"].to_numpy(float), day_per_week, rec_p)
    decision = (enpv > tau).astype(int)
    loA, hiA = calibrate.pd_intervals(cpd, kA["k"], kA["floor"])
    submission.write_a(pd.DataFrame({"applicant_id": pool["applicant_id"].astype(str), "decision": decision,
                                     "predicted_pd": cpd, "pd_lower_90": loA, "pd_upper_90": hiA}))
    print(f"\nscored {len(pool):,} | approve={decision.mean():.3f} | mean PD={cpd.mean():.3f}")

    # ---- B: marginal timing cohort curves; intervals tuned on val realized ----
    marg = np.zeros(N_WEEKS)
    dwk = np.ceil(labeled.loc[labeled.default_flag == 1, "days_to_default"].to_numpy() / 7).clip(1, N_WEEKS).astype(int)
    for k in dwk:
        marg[k - 1] += 1
    marg /= marg.sum()
    coh = cohorts.assign_cohort(pool).to_numpy()
    cif_pool = np.cumsum(cpd[:, None] * np.tile(marg, (len(pool), 1)), axis=1)

    # tune B interval k on labeled-val realized trajectory of OUR approved set
    val = va[va["default_flag"].notna()].copy()
    Xv, _ = features.build_features(val, fs)
    cpd_v = cal.predict(cv.apply_stack(meta, {b: models.proba(final_base[b], Xv) for b in BASES})
                        if winner == "stack" else models.proba(final_base["logistic"], Xv))
    enpv_v = cv.enpv_from_pd(cpd_v, cv.expand_week_probs(tm, classes, Xv),
                             val["requested_amount"].to_numpy(float), day_per_week, cv.recovery_rate(recmodel, Xv))
    appr_v = enpv_v > tau
    cohv = cohorts.assign_cohort(val).to_numpy()
    yv = val["default_flag"].to_numpy()
    dwv = np.clip(np.nan_to_num(np.where(yv == 1, np.ceil(val["days_to_default"].to_numpy() / 7), 0)), 0, N_WEEKS).astype(int)
    cif_v = np.cumsum(cpd_v[:, None] * np.tile(marg, (len(val), 1)), axis=1)
    preds, reals, ns = [], [], []
    for w in range(1, N_WEEKS + 1):
        sel = appr_v & (cohv == w)
        if sel.sum() == 0:
            continue
        preds.append(cif_v[sel].mean(axis=0))
        reals.append(np.array([np.mean((yv[sel] == 1) & (dwv[sel] <= a) & (dwv[sel] >= 1)) for a in range(1, N_WEEKS + 1)]))
        ns.append(np.full(N_WEEKS, sel.sum()))
    kB = calibrate.tune_b_interval(np.concatenate(preds), np.concatenate(reals), np.concatenate(ns))
    print(f"B-interval k={kB['k']:.2f} | val cohort/age coverage={kB['coverage']:.2f}")

    overall = cif_pool[decision == 1].mean(axis=0) if (decision == 1).any() else cif_pool.mean(axis=0)
    rows = []
    for w in range(1, N_WEEKS + 1):
        sel = (coh == w) & (decision == 1)
        n = int(sel.sum())
        point = cif_pool[sel].mean(axis=0) if n else overall
        se = np.sqrt(np.clip(point * (1 - point), 0, None) / max(n, 1))
        half = np.maximum(kB["k"] * se, kB["floor"])
        for a in range(1, N_WEEKS + 1):
            p = float(point[a - 1]); h = float(half[a - 1])
            rows.append((w, a, p, max(0.0, p - h), min(1.0, p + h)))
    submission.write_b(pd.DataFrame(rows, columns=submission.COLUMNS_B))

    paths.CACHE_DIR.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(paths.CACHE_DIR / "phase5_preds.npz",
                        applicant_id=pool["applicant_id"].astype(str).to_numpy(), decision=decision,
                        pd_cal=cpd, enpv=enpv, tau=tau, winner=winner,
                        oof_pnl=res[winner]["pnl"], oof_auc=res[winner]["auc"])

    print("\n[validate]")
    ok = validate.run()
    print("\n" + "=" * 74)
    print(f"PHASE 5: {'OK' if ok else 'FAILED'} | OOF AUC={res[winner]['auc']:.4f} "
          f"OOF P&L=${res[winner]['pnl']:,.0f} (vs Phase-2 logistic OOF ${res['logistic']['pnl']:,.0f})")
    print("Note: re-run `python run.py phase3` to regenerate C on the richer features.")
    print("=" * 74)
    return ok


if __name__ == "__main__":
    raise SystemExit(0 if run() else 1)
